// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXc3IFbjpsH7KAsLNoi50NlVn7bGyzr0o',
    appId: '1:216776254887:web:d5531c4fb2d26f08404282',
    messagingSenderId: '216776254887',
    projectId: 'current-a-la-te',
    authDomain: 'current-a-la-te.firebaseapp.com',
    storageBucket: 'current-a-la-te.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7Wmoq_ayXl942DX3DAIPOycn2LhEKIs',
    appId: '1:216776254887:android:2626c3ffa38dd03c404282',
    messagingSenderId: '216776254887',
    projectId: 'current-a-la-te',
    storageBucket: 'current-a-la-te.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClDqmMDOujP0l0ZqRiLZje9PduZre7pcM',
    appId: '1:216776254887:ios:b2cb2e119aa2ac92404282',
    messagingSenderId: '216776254887',
    projectId: 'current-a-la-te',
    storageBucket: 'current-a-la-te.firebasestorage.app',
    iosBundleId: 'com.rceb98.current-a-la-te',
  );

}